### ISSUE TITLE
Error Rendering on Mac

### ISSUE THREAD

**Issue by ansonphong** [grz0zrg/tools-povray#1]
@grz0zrg Thanks, this is a great start to what I'm looking for, and it compliments the POV-Ray color coding that @h-a-n-n-e-s put together wonderfully. I am testing it on Mac right now, and I get this error. Haven't tested on Windows yet.

![image](https://cloud.githubusercontent.com/assets/4825055/18896446/0bb15d6c-84df-11e6-9b80-ed434f75d9b4.png)

I have POV-Unofficial 3.7 installed, how would I define the path to run? If there was a way to configure this in the settings that would be great.

**Comment by ansonphong** [comment]
I also tested this on PC, and this is the error I get:

![image](https://cloud.githubusercontent.com/assets/4825055/18899548/f4d356b4-84f6-11e6-92ef-9b8652aa60f5.png)

I haven't been able to get it to work yet, although I'm currently studying the source code to see how to configure things manually, it's not clear yet. Any help getting this to work would be appreciated.

**Comment by grz0zrg** [comment]
Hello, thank you for testing this out, is Mac POV-Unofficial executable named "povray"? I made this package quickly from another one and removed the "path" settings but will look into re-adding it anyway because it may be useful for peoples who use different distributions of POV-Ray.

**Comment by grz0zrg** [comment]
Just added a way to configure POV-Ray path, please test and report any issues, thank you.

**Comment by grz0zrg** [comment]
Did a quick update to add Windows support, it work but does not reuse the same rendering window...

As for Mac support, it seem POV-Ray does not allow command-line parameters on Mac but maybe i am missing something...

**Comment by grz0zrg** [comment]
I am closing this issue as i think it is working well for Windows now and since it is possible to set the POV-Ray executable path, it should work on all platforms, even with unofficial versions of POV-Ray as long as it support command-line options.
